[package]
name = "kvfast"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap2 = "0.9"
tempfile = "3.10"
boomphf = "0.6.0"
bincode = "1.3" 
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
tempfile = "3.10"

[lib]
name = "kvfast_lib"
path = "src/lib.rs"
